# Generated by Django 4.2.17 on 2025-01-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_salsa_recurrence_maplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salsa',
            name='end_recurring_date',
            field=models.DateField(blank=True, help_text='Last date of recurrence', null=True),
        ),
        migrations.AddField(
            model_name='salsa',
            name='recurrence_interval',
            field=models.IntegerField(blank=True, default=1, help_text='Interval for recurrence (e.g., every 2 weeks)', null=True),
        ),
    ]
