# Generated by Django 4.2.17 on 2025-01-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_salsa_end_recurring_date_salsa_recurrence_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='salsa',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
