# Generated by Django 4.2.17 on 2025-02-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_salsa_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='salsa',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
