# Generated by Django 4.2.17 on 2025-02-03 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_salsa_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='salsa',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salsa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
